/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;


/**
 *
 * @author GIGABYTE
 */
public class PagVistaCliente extends javax.swing.JFrame {

    /**
     * Creates new form PagVistaCliente
     */
    public PagVistaCliente() {
        initComponents();
//        this.setLocationRelativeTo(null);
        titulotxt.setHorizontalAlignment(SwingConstants.CENTER);
        
        //PARA EL BOTON DE REFRESCAR
       refrescarPag.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e){
            
            PagVistaCliente nuevo=new PagVistaCliente();
            nuevo.setVisible(true);
            nuevo.setLocationRelativeTo(null);
            dispose();
        }
        });
       
       //PARA EL JScrollPane que irá anexado al panelProducto
       JScrollPane scrollPane = new JScrollPane();
       
       scrollPane.setBounds(60, 150, 1000, 590); //el scrollPane inicialmente tendra el tamaño del panelProducto (no aparecerán scrolls en un primer momento)
       scrollPane.setViewportView(panelProducto); //es como si scrollPane tomara poseción de panelProducto y ahora se hubieran combinado
       scrollPane.getViewport().setView(panelProducto);
       
        //Implementar paneles al panel background
        JLabel xdd=new JLabel();
        xdd.setText("ptm");
        panelBackground.add(xdd);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelPresentacion = new javax.swing.JPanel();
        titulotxt = new javax.swing.JLabel();
        refrescarPag = new javax.swing.JLabel();
        panelProducto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(51, 51, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPresentacion.setBackground(new java.awt.Color(255, 153, 153));
        panelPresentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulotxt.setText("ESTO ES UN TITULO");
        panelPresentacion.add(titulotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 1130, 22));

        refrescarPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refrescar.png"))); // NOI18N
        panelPresentacion.add(refrescarPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 12, -1, -1));

        panelBackground.add(panelPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 100));

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));
        panelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBackground.add(panelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 1000, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagVistaCliente().setVisible(true);
            }
        });
    }

     public ImageIcon scaleImage(ImageIcon icon, int w, int h) {
        int nw = icon.getIconWidth();
        int nh = icon.getIconHeight();

        if (icon.getIconWidth() > w) {
            nw = w;
            nh = (nw * icon.getIconHeight()) / icon.getIconWidth();
        }

        if (nh > h) {
            nh = h;
            nw = (icon.getIconWidth() * nh) / icon.getIconHeight();
        }

        return new ImageIcon(icon.getImage().getScaledInstance(nw, nh, Image.SCALE_DEFAULT));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelPresentacion;
    private javax.swing.JPanel panelProducto;
    public javax.swing.JLabel refrescarPag;
    private javax.swing.JLabel titulotxt;
    // End of variables declaration//GEN-END:variables
}
