/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class ProductoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductoPanel
     */
    public ProductoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Buscadortxt = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        comboOrdenar = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cantidadProductos = new javax.swing.JLabel();
        btnLupa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableProductoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducto);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 69, 760, 348));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad de productos: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 435, -1, -1));

        Buscadortxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Buscadortxt.setForeground(new java.awt.Color(204, 204, 204));
        Buscadortxt.setText("Ingrese nombre del producto");
        Buscadortxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Buscadortxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscadortxtMousePressed(evt);
            }
        });
        add(Buscadortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 242, 30));

        btnAgregar.setText("Agregar");
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 461, 91, 37));

        btnModif.setText("Modificar");
        add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 460, 95, 39));

        btnElim.setText("Eliminar");
        add(btnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 460, 95, 39));

        comboOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin ordenar", "Mayores ventas", "Valor de stock", "Stock inicial", "Stock actual", "Nombre producto", " " }));
        add(comboOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 120, 28));

        jRadioButton1.setText("mayor a menor");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        jRadioButton2.setText("menor a mayor");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        cantidadProductos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cantidadProductos.setText("jLabel1");
        add(cantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 60, 30));

        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupita.png"))); // NOI18N
        add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadortxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadortxtMousePressed
        if(Buscadortxt.getText().equals("Ingrese nombre del producto")){
            Buscadortxt.setText("");
            Buscadortxt.getCaret().setVisible(true);
            Buscadortxt.setForeground(Color.black);
        }
     
    }//GEN-LAST:event_BuscadortxtMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
            if(Buscadortxt.getText().isEmpty()){
            Buscadortxt.setText("Ingrese nombre del producto");
            Buscadortxt.setForeground(Color.gray);
        } 
            Buscadortxt.getCaret().setVisible(false);
    }//GEN-LAST:event_formMousePressed

    private void tableProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMousePressed
        if(Buscadortxt.getText().isEmpty()){
            Buscadortxt.setText("Ingrese nombre del producto");
            Buscadortxt.setForeground(Color.gray);
        } 
            Buscadortxt.getCaret().setVisible(false);
    }//GEN-LAST:event_tableProductoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Buscadortxt;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnElim;
    public javax.swing.JLabel btnLupa;
    public javax.swing.JButton btnModif;
    public javax.swing.JLabel cantidadProductos;
    public javax.swing.JComboBox<String> comboOrdenar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableProducto;
    // End of variables declaration//GEN-END:variables
}
