/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Configuracion;
import Model.Producto;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Controller.*;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
/**
 *
 * @author usuario
 */
public class ProductoPanel extends javax.swing.JPanel {
    private Object[] obj;
    private boolean habilitadoMod;
    /**
     * Creates new form ProductoPanel
     */
    public ProductoPanel() {
        
        initComponents();
       llenarListaCategoria();
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
        habilitadoMod = true;
        this.panelModificar.setVisible(false);
        btnCancelarBusqueda.setVisible(false);
        this.filtroCategoriastxt.setVisible(false);
        this.radioAscendente.setVisible(false);
        this.radioDescendente.setVisible(false);

        this.grupoBtnEliminar.add(this.RadioElimSelect);
        this.grupoBtnEliminar.add(this.RadioElimVencidos);
        this.grupoBtnEliminar.add(this.RadioElimAgotados);
        this.RadioElimSelect.setSelected(true);

        this.grupoBtnOrdenar.add(this.radioDescendente);
        this.grupoBtnOrdenar.add(this.radioAscendente);
        this.radioAscendente.setSelected(true);

//        ImageIcon user=new ImageIcon(getClass().getResource("../Images/cerrar.png"));
//        Icon userZ=new ImageIcon(user.getImage().getScaledInstance(this.btnCancelarBusqueda.getWidth(),this.btnCancelarBusqueda.getHeight(),Image.SCALE_DEFAULT));
//        this.btnCancelarBusqueda.setIcon(userZ);
//         this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnEliminar = new javax.swing.ButtonGroup();
        grupoBtnOrdenar = new javax.swing.ButtonGroup();
        panelModificar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCategoria = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        textValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        textValorStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelGuardar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelVencimiento = new javax.swing.JLabel();
        labelStockActual = new javax.swing.JLabel();
        labelStockInicial = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JLabel();
        btnLupa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filtroCategoriastxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        comboOrdenar = new javax.swing.JComboBox<>();
        RadioElimSelect = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnElim = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioAscendente = new javax.swing.JRadioButton();
        radioDescendente = new javax.swing.JRadioButton();
        scrollCategoria = new javax.swing.JScrollPane();
        listaCategoria = new javax.swing.JList<>();
        RadioElimAgotados = new javax.swing.JRadioButton();
        RadioElimVencidos = new javax.swing.JRadioButton();
        btnAplicarCambios = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Buscadortxt = new javax.swing.JTextField();
        cantidadProductos = new javax.swing.JLabel();
        btnCancelarBusqueda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        panelMod = new javax.swing.JPanel();
        btnModif = new javax.swing.JLabel();
        panelDetalles = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelModificar.setBackground(new java.awt.Color(0,0,0,200));
        panelModificar.setPreferredSize(new java.awt.Dimension(600, 349));
        panelModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModificarMouseClicked(evt);
            }
        });
        panelModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel2.setText("MODIFICAR  STOCK");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nombre:");

        textNombre.setForeground(new java.awt.Color(204, 204, 204));
        textNombre.setText("jTextField1");
        textNombre.setBorder(null);
        textNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNombreMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categoría:");

        textCategoria.setForeground(new java.awt.Color(204, 204, 204));
        textCategoria.setText("jTextField2");
        textCategoria.setBorder(null);
        textCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCategoriaMouseClicked(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        textValor.setForeground(new java.awt.Color(204, 204, 204));
        textValor.setText("jTextField3");
        textValor.setBorder(null);
        textValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textValorMouseClicked(evt);
            }
        });
        textValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textValorKeyTyped(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Valor c/u:");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        textValorStock.setForeground(new java.awt.Color(204, 204, 204));
        textValorStock.setText("jTextField4");
        textValorStock.setBorder(null);
        textValorStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textValorStockMouseClicked(evt);
            }
        });
        textValorStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textValorStockKeyTyped(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Valor stock:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelGuardar.setBackground(new java.awt.Color(204, 155, 64));
        panelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGuardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGuardarMouseEntered(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Guardar cambios");

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelCancelar.setBackground(new java.awt.Color(204, 155, 64));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCancelarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelarMouseEntered(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cancelar");

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        labelEstado.setForeground(new java.awt.Color(153, 153, 153));
        labelEstado.setText("Estado:");

        labelVencimiento.setForeground(new java.awt.Color(153, 153, 153));
        labelVencimiento.setText("Vencimiento:");

        labelStockActual.setForeground(new java.awt.Color(153, 153, 153));
        labelStockActual.setText("Stock Actual:");

        labelStockInicial.setForeground(new java.awt.Color(153, 153, 153));
        labelStockInicial.setText("Stock inicial:");

        labelCodigo.setForeground(new java.awt.Color(153, 153, 153));
        labelCodigo.setText("Codigo: ");

        jLabel1.setForeground(new java.awt.Color(130, 130, 130));
        jLabel1.setText("Informacion del producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(labelStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(labelStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(labelVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(textValorStock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(labelCodigo)
                        .addGap(14, 14, 14)
                        .addComponent(labelStockInicial)
                        .addGap(18, 18, 18)
                        .addComponent(labelStockActual)
                        .addGap(14, 14, 14)
                        .addComponent(labelVencimiento)
                        .addGap(14, 14, 14)
                        .addComponent(labelEstado))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textValorStock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelModificar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 530, 430));

        add(panelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad de productos: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refrescar.png"))); // NOI18N
        btnRefrescar.setText("jLabel1");
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 30));

        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupita.png"))); // NOI18N
        btnLupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLupaMouseClicked(evt);
            }
        });
        jPanel2.add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 40, 30));

        jPanel1.setBackground(new java.awt.Color(255, 221, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filtroCategoriastxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        filtroCategoriastxt.setForeground(new java.awt.Color(204, 204, 204));
        filtroCategoriastxt.setText("Ingrese categoría");
        filtroCategoriastxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                filtroCategoriastxtMousePressed(evt);
            }
        });
        filtroCategoriastxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroCategoriastxtKeyPressed(evt);
            }
        });
        jPanel1.add(filtroCategoriastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Filtro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 30));

        comboFiltro.setBackground(new java.awt.Color(220, 193, 138));
        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin filtro", "Por categoría", "Stocks caducados", "Stocks vigentes", "Stocks agotados" }));
        comboFiltro.setBorder(null);
        comboFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });
        jPanel1.add(comboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 28));

        comboOrdenar.setBackground(new java.awt.Color(220, 193, 138));
        comboOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin ordenar", "Cantidad de ventas", "Ganancias", "Cantidad inicial", "Cantidad actual", "Nombre de producto" }));
        comboOrdenar.setBorder(null);
        comboOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(comboOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 28));

        RadioElimSelect.setBackground(new java.awt.Color(255, 221, 158));
        RadioElimSelect.setText("Por selección");
        RadioElimSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadioElimSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Eliminar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 50, 30));

        btnElim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/basureroZ.png"))); // NOI18N
        btnElim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Ordenar por:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        radioAscendente.setBackground(new java.awt.Color(255, 221, 158));
        radioAscendente.setText("menor a mayor");
        radioAscendente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(radioAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        radioDescendente.setBackground(new java.awt.Color(255, 221, 158));
        radioDescendente.setText("mayor a menor");
        radioDescendente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(radioDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        listaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCategoriaMouseClicked(evt);
            }
        });
        scrollCategoria.setViewportView(listaCategoria);

        jPanel1.add(scrollCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 80));

        RadioElimAgotados.setBackground(new java.awt.Color(255, 221, 158));
        RadioElimAgotados.setText("Productos agotados");
        RadioElimAgotados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadioElimAgotados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 413, -1, 30));

        RadioElimVencidos.setBackground(new java.awt.Color(255, 221, 158));
        RadioElimVencidos.setText("Productos vencidos");
        RadioElimVencidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(RadioElimVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, -1, 30));

        btnAplicarCambios.setBackground(new java.awt.Color(204, 155, 64));
        btnAplicarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAplicarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAplicarCambiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAplicarCambiosMouseExited(evt);
            }
        });

        jLabel14.setText("Aplicar");

        javax.swing.GroupLayout btnAplicarCambiosLayout = new javax.swing.GroupLayout(btnAplicarCambios);
        btnAplicarCambios.setLayout(btnAplicarCambiosLayout);
        btnAplicarCambiosLayout.setHorizontalGroup(
            btnAplicarCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAplicarCambiosLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        btnAplicarCambiosLayout.setVerticalGroup(
            btnAplicarCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnAplicarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 160, 520));

        Buscadortxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Buscadortxt.setForeground(new java.awt.Color(204, 204, 204));
        Buscadortxt.setText("Ingrese nombre del producto");
        Buscadortxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscadortxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscadortxtMousePressed(evt);
            }
        });
        jPanel2.add(Buscadortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 242, 30));

        cantidadProductos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cantidadProductos.setText("2");
        jPanel2.add(cantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 60, 40));

        btnCancelarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar.png"))); // NOI18N
        btnCancelarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCancelarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 30, 30));

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tableProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableProductoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducto);
        if (tableProducto.getColumnModel().getColumnCount() > 0) {
            tableProducto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableProducto.getColumnModel().getColumn(0).setMaxWidth(50);
            tableProducto.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableProducto.getColumnModel().getColumn(8).setPreferredWidth(60);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 360));

        panelMod.setBackground(new java.awt.Color(204, 155, 64));
        panelMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelModMouseExited(evt);
            }
        });

        btnModif.setText("Modificar");

        javax.swing.GroupLayout panelModLayout = new javax.swing.GroupLayout(panelMod);
        panelMod.setLayout(panelModLayout);
        panelModLayout.setHorizontalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnModif)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelModLayout.setVerticalGroup(
            panelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 100, 37));
        panelMod.getAccessibleContext().setAccessibleName("");

        panelDetalles.setBackground(new java.awt.Color(204, 155, 64));
        panelDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDetallesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDetallesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDetallesMouseExited(evt);
            }
        });

        jLabel15.setText("Más detalles");

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 100, 37));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadortxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadortxtMousePressed
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
        if (Buscadortxt.getText().equals("Ingrese nombre del producto")) {
            Buscadortxt.setText("");
            Buscadortxt.setForeground(Color.black);
        }
        tableProducto.clearSelection(); //limpiar seleccion de tabla
        Buscadortxt.getCaret().setVisible(true);
    }//GEN-LAST:event_BuscadortxtMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      this.scrollCategoria.setVisible(false);
      this.btnAplicarCambios.setVisible(true);
        if (Buscadortxt.getText().isEmpty()) {
            Buscadortxt.setText("Ingrese nombre del producto");
            Buscadortxt.setForeground(Color.gray);
        }
        if (filtroCategoriastxt.getText().isEmpty()) {
            filtroCategoriastxt.setText("Ingrese categoría");
            filtroCategoriastxt.setForeground(Color.gray);
        }
        tableProducto.clearSelection();
        Buscadortxt.getCaret().setVisible(false);
        filtroCategoriastxt.getCaret().setVisible(false);
    }//GEN-LAST:event_formMousePressed

    private void tableProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMousePressed
       this.scrollCategoria.setVisible(false);
       this.btnAplicarCambios.setVisible(true);
        if (Buscadortxt.getText().isEmpty()) {
            Buscadortxt.setText("Ingrese nombre del producto");
            Buscadortxt.setForeground(Color.gray);
        }
        tableProducto.setDefaultEditor(Object.class, null);
        Buscadortxt.getCaret().setVisible(false);
        filtroCategoriastxt.getCaret().setVisible(false);
    }//GEN-LAST:event_tableProductoMousePressed

    private void filtroCategoriastxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtroCategoriastxtMousePressed
        if (filtroCategoriastxt.getText().equals("Ingrese categoría")) {
            filtroCategoriastxt.setText("");
            filtroCategoriastxt.setForeground(Color.black);
        }
        filtroCategoriastxt.getCaret().setVisible(true);
        if(!(Configuracion.arrProductos.getIndice()==0)){
            this.scrollCategoria.setVisible(true);
        }
        this.btnAplicarCambios.setVisible(false);
        tableProducto.clearSelection();
    }//GEN-LAST:event_filtroCategoriastxtMousePressed

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
        if (this.comboFiltro.getSelectedIndex() == 1) {
            filtroCategoriastxt.setText("Ingrese categoría");
            filtroCategoriastxt.setForeground(Color.gray);
            filtroCategoriastxt.setVisible(true);
            filtroCategoriastxt.getCaret().setVisible(false);
        } else {
            filtroCategoriastxt.setVisible(false);
        }
        tableProducto.clearSelection();
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void comboOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrdenarActionPerformed
       this.scrollCategoria.setVisible(false);
       this.btnAplicarCambios.setVisible(true);
        if (this.comboOrdenar.getSelectedIndex() != 0) {
            this.radioAscendente.setVisible(true);
            this.radioDescendente.setVisible(true);
        } else {
            this.radioAscendente.setVisible(false);
            this.radioDescendente.setVisible(false);
        }
    }//GEN-LAST:event_comboOrdenarActionPerformed
    private void llenarDatos(){
        textNombre.setText((String) obj[1]);
        textNombre.setForeground(new Color(204,204,204));
        textCategoria.setText((String) obj[2]);
        textCategoria.setForeground(new Color(204,204,204));
        textValor.setText(""+(Double) obj[3]);
        textValor.setForeground(new Color(204,204,204));
        textValorStock.setText(""+(((Double) obj[3])*((Integer) obj[4])));
        textValorStock.setForeground(new Color(204,204,204));
        labelCodigo.setText("Codigo: "+(String) obj[0]);
        labelStockInicial.setText("Stock Inicial: "+(Integer) obj[4]);
        labelStockActual.setText("Stock Actual: "+(Integer) obj[5]);
        labelVencimiento.setText("Fecha de Vencimiento: "+
                Configuracion.arrProductos.getArregloP()[tableProducto.getSelectedRow()].getFechaVencimiento());
        labelEstado.setText("Estado: "+(String) obj[8]);
    }
    private void iniciarModificacion(){
        int index = Configuracion.arrProductos.buscar((String) this.obj[0]);
        Producto[] arreglo = Configuracion.arrProductos.getArregloP();
        arreglo[index].setNombreProducto(textNombre.getText());
        arreglo[index].setCategoria(textCategoria.getText());
        arreglo[index].setValorXUnidad(Float.parseFloat(textValor.getText()));
        arreglo[index].setValorTotalStock(Float.parseFloat(textValorStock.getText()));
        Configuracion.arrProductos.setArregloP(arreglo);
        try{
            Configuracion.serial.serializar("archivoProductos.dat",Configuracion.arrProductos); 
            
        } catch (IOException ex) {
            //F
        }
    }
    private void textNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreMouseClicked
        textNombre.setText("");
        textNombre.setForeground(Color.black);

    }//GEN-LAST:event_textNombreMouseClicked

    private void textCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCategoriaMouseClicked
        textCategoria.setText("");
        textCategoria.setForeground(Color.black);
    }//GEN-LAST:event_textCategoriaMouseClicked

    private void textValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textValorMouseClicked
        textValor.setText("");
        textValor.setForeground(Color.black);
    }//GEN-LAST:event_textValorMouseClicked

    private void textValorStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textValorStockMouseClicked
        textValorStock.setText("");
        textValorStock.setForeground(Color.black);
    }//GEN-LAST:event_textValorStockMouseClicked

    private void panelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseClicked
        iniciarModificacion();
        DefaultTableModel modelo = new DefaultTableModel(Configuracion.arrProductos.data(), Configuracion.arrProductos.header());
        tableProducto.setModel(modelo);
        panelModificar.setVisible(false);
        llenarComponentes();
        //terminar
    }//GEN-LAST:event_panelGuardarMouseClicked

    private void panelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseExited
        panelGuardar.setBackground(new Color(204,155,64));
    }//GEN-LAST:event_panelGuardarMouseExited

    private void panelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseEntered
        panelGuardar.setBackground(new Color(210, 168, 89));
    }//GEN-LAST:event_panelGuardarMouseEntered

    private void panelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseClicked
        panelModificar.setVisible(false);
        llenarComponentes();
    }//GEN-LAST:event_panelCancelarMouseClicked

    private void panelCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseExited
        panelCancelar.setBackground(new Color(204,155,64));
    }//GEN-LAST:event_panelCancelarMouseExited

    private void panelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseEntered
        panelCancelar.setBackground(new Color(210, 168, 89));
    }//GEN-LAST:event_panelCancelarMouseEntered

    private void panelModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelModificarMouseClicked

    private void textValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorKeyTyped
        try{
            float valor = Float.parseFloat(textValor.getText()+evt.getKeyChar())*(Integer) obj[3];
            textValorStock.setText(valor+"");
            textValorStock.setForeground(Color.BLACK);
        }catch(Exception e){
            float valor = Float.parseFloat(""+evt.getKeyChar())*(Integer) obj[3];
            textValorStock.setText(valor+"");
            textValorStock.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_textValorKeyTyped

    private void textValorStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorStockKeyTyped
        try{
            float valor = Float.parseFloat(textValorStock.getText()+evt.getKeyChar())/(Integer) obj[3];
            textValor.setText(valor+"");
            textValor.setForeground(Color.BLACK);
        }catch(Exception e){
            float valor = Float.parseFloat(""+evt.getKeyChar())/(Integer) obj[3];
            textValor.setText(valor+"");
            textValor.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_textValorStockKeyTyped

    private void panelModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModMouseClicked
     DefaultTableModel dtm = (DefaultTableModel) tableProducto.getModel();
     this.scrollCategoria.setVisible(false);
     this.btnAplicarCambios.setVisible(true);
        panelMod.setBackground(new Color(204,155,64));
        int index=0;
        try{
            index=tableProducto.getSelectedRow();
            this.obj = new Object[] {
                dtm.getValueAt(index, 0),
                dtm.getValueAt(index, 1),
                dtm.getValueAt(index, 2),
                dtm.getValueAt(index, 3),
                dtm.getValueAt(index, 4),
                dtm.getValueAt(index, 5),
                dtm.getValueAt(index, 6),
                dtm.getValueAt(index, 7),
                dtm.getValueAt(index, 8)
            };
            llenarDatos();
            panelModificar.setVisible(true);
            limpiarComponentes();
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "¡Primero debe seleccionar un stock de inventario!");
        }
    }//GEN-LAST:event_panelModMouseClicked
    private void llenarComponentes(){
        this.habilitadoMod = true;
        tableProducto.setVisible(true);
    }
    private void limpiarComponentes(){
        this.habilitadoMod = false;
        tableProducto.clearSelection();
        tableProducto.setVisible(false);
        //tableProducto.setVisible(true);
    }
    private void panelModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModMouseEntered
        panelMod.setBackground(new Color(210, 168, 89));
    }//GEN-LAST:event_panelModMouseEntered

    private void panelModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModMouseExited
        if(this.habilitadoMod)
            panelMod.setBackground(new Color(204,155,64));
    }//GEN-LAST:event_panelModMouseExited

    private void filtroCategoriastxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroCategoriastxtKeyPressed
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
    }//GEN-LAST:event_filtroCategoriastxtKeyPressed

    private void listaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCategoriaMouseClicked
   this.filtroCategoriastxt.setText(this.listaCategoria.getSelectedValue());
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
    }//GEN-LAST:event_listaCategoriaMouseClicked

    private void btnLupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLupaMouseClicked
    
    }//GEN-LAST:event_btnLupaMouseClicked

    private void panelDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDetallesMouseClicked
           this.panelDetalles.setBackground(new Color(204,155,64));
        this.scrollCategoria.setVisible(false);
        this.btnAplicarCambios.setVisible(true);
        int seleccionado = this.tableProducto.getSelectedRow();
        if (seleccionado != -1) {
            
            String codigo = tableProducto.getValueAt(seleccionado, 0).toString();
            int ubicacionProducto=Configuracion.arrProductos.buscar(codigo);
            ControllerDetalles controller=new ControllerDetalles(Configuracion.arrProductos.getArregloP()[ubicacionProducto]);
            controller.run();
        }else{
          JOptionPane.showMessageDialog(null, "¡Primero debe seleccionar un stock de inventario!");  
        }
        
        
    }//GEN-LAST:event_panelDetallesMouseClicked

    private void panelDetallesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDetallesMouseExited
         if(this.habilitadoMod)
        this.panelDetalles.setBackground(new Color(204,155,64));
    }//GEN-LAST:event_panelDetallesMouseExited

    private void panelDetallesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDetallesMouseEntered
      this.panelDetalles.setBackground(new Color(210, 168, 89));
    }//GEN-LAST:event_panelDetallesMouseEntered

    private void btnAplicarCambiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAplicarCambiosMouseEntered
     this.btnAplicarCambios.setBackground(new Color(210, 168, 89));
    }//GEN-LAST:event_btnAplicarCambiosMouseEntered

    private void btnAplicarCambiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAplicarCambiosMouseExited
          if(this.habilitadoMod)
        this.btnAplicarCambios.setBackground(new Color(204,155,64));
    }//GEN-LAST:event_btnAplicarCambiosMouseExited

    
        public void llenarListaCategoria() {
        DefaultListModel agregarElementos = new DefaultListModel();

        boolean esRepetido=false;

        for (int i = 0; i <Configuracion.arrProductos.getIndice(); i++) {
            esRepetido=false;
         if(agregarElementos.isEmpty()){
             agregarElementos.addElement(Configuracion.arrProductos.getArregloP()[i].getCategoria());
         }else{
             for(int j=0;j<agregarElementos.getSize();j++){
                 if(Configuracion.arrProductos.getArregloP()[i].getCategoria().equals(agregarElementos.get(j))){
                    esRepetido=true;
                 }
             }
               if(esRepetido==false){
                      agregarElementos.addElement(Configuracion.arrProductos.getArregloP()[i].getCategoria());
                 }
         }
        }
        this.listaCategoria.setModel(agregarElementos);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Buscadortxt;
    public javax.swing.JRadioButton RadioElimAgotados;
    public javax.swing.JRadioButton RadioElimSelect;
    public javax.swing.JRadioButton RadioElimVencidos;
    public javax.swing.JPanel btnAplicarCambios;
    public javax.swing.JLabel btnCancelarBusqueda;
    public javax.swing.JLabel btnElim;
    public javax.swing.JLabel btnLupa;
    private javax.swing.JLabel btnModif;
    public javax.swing.JLabel btnRefrescar;
    public javax.swing.JLabel cantidadProductos;
    public javax.swing.JComboBox<String> comboFiltro;
    public javax.swing.JComboBox<String> comboOrdenar;
    public javax.swing.JTextField filtroCategoriastxt;
    public javax.swing.ButtonGroup grupoBtnEliminar;
    public javax.swing.ButtonGroup grupoBtnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelStockActual;
    private javax.swing.JLabel labelStockInicial;
    private javax.swing.JLabel labelVencimiento;
    private javax.swing.JList<String> listaCategoria;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelMod;
    private javax.swing.JPanel panelModificar;
    public javax.swing.JRadioButton radioAscendente;
    public javax.swing.JRadioButton radioDescendente;
    private javax.swing.JScrollPane scrollCategoria;
    public javax.swing.JTable tableProducto;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textValor;
    private javax.swing.JTextField textValorStock;
    // End of variables declaration//GEN-END:variables
}
